### ISSUE TITLE
Very problematic behavior after upgrading to 0.26.1

### ISSUE THREAD

**Issue by spapas** [EmilStenstrom/django-components#239]
I've got a simple component named card. Here's the template 

```html
<div class="card mb-3 {{ color }} {{ border_color }}">
  <h5 class="card-header {{ header_color }} {{ header_text_color }}">
    {{ title }}</h5>

  <div class="card-body {{ color }} {{ text_color }}">
    {% slot "body" %}{% endslot %}
  </div>
</div>
```

and the function:

```py
@component.register("card")
class Card(component.Component):
    template_name = "components/card.html"

    # This component takes one parameter, a date string to show in the template
    def get_context_data(  # noqa PLR0913
        self, title, color="", text_color="", header_color="", header_text_color="", border_color=""
    ):
        return {
            "title": title,
            "color": color,
            "text-color": text_color,
            "header_color": header_color,
            "header_text_color": header_text_color,
            "border_color": border_color,
        }

    class Media:
        css = ""
        js = ""
```

Now, this was working flawlessly when I was using {% slot %} to render my template. However, after I upgraded to the new version and used {% fill %} instead it works *only* when I *include* a partial template with component on my template! 

So, Let's suppose I have a template named foo.html and I want to include this component:

```
{% component_block "card" "Test"  %}
{% fill "body" %}
  <div>test</div>
{% endfill %}
{% endcomponent_block %}
```

If I add this *directly* on foo.html I'll get the following error:

```
Traceback (most recent call last):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django_extensions\management\technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader_tags.py", line 294, in do_extends
    if nodelist.get_nodes_by_type(ExtendsNode):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
AttributeError: 'list' object has no attribute 'get_nodes_by_type'
```

i.e it seems that it tries to call get_nodes_by_type on a list (!)

However, if I create a file named `foo_partial.html`, put the above snippet inside that file and include it on my template using `{% include "foo_partial.html" %}` it works without problems! 

Please notice I didn't change anything else while upgrading to the new version, I only changed {% slot %} to {% fill %}. Can you please clarify what is the problem? 

BR,
Serafeim

**Comment by lemontheme** [comment]
Hi there. As the author of the changes in this release, I'm sorry you ran into this bug. Thanks for reporting – and, even better, proposing a possible fix!

I'm scratching my head at how this made it past our tests, as this is a pretty simple case. I'm investigating right now and will give an update later

**Comment by spapas** [comment]
Hello @lemontheme unfortunately this is not a public project so I can't show the whole source code. I understand that the reason is probably because of some of my configuration or template structure. 

Beyond researching this more, I'd like to ask you to try using "extends" in your resulting template. So create a "base.html" with some basic structure and a "page.html" that `{% extends "base.html" %}`. Then render the components in "page.html".

If this still doesn't reproduce the error, I'm pasting here some of my requirements and template settings in case something seems fishy:

```
django==4.1.7
django_components==0.26.1
```

and my template settings: 

```

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ehcg.core.context_processors.default_cp",
            ],
            "builtins": [
                "django_components.templatetags.component_tags",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                        "django_components.template_loader.Loader",
                    ],
                )
            ],
        },
    }
]
```

If still it ain't possible to reproduce the error I can try creating a simple project that shows that behavior, but this may need some time to mix and match with the existing configuration...
