### ISSUE TITLE
Django-components not compatible with Dynaconf

### ISSUE THREAD

**Issue by mjmare** [EmilStenstrom/django-components#374]
When loading Django Components, I'm getting this error:
```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/mjm/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/mjm/.pyenv/versions/3.11.4/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django_components/apps.py", line 8, in ready
    self.module.autodiscover()
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django_components/__init__.py", line 27, in autodiscover
    dirs = loader.get_dirs()
           ^^^^^^^^^^^^^^^^^
  File "/Users/mjm/.pyenv/versions/cummulus-epd/lib/python3.11/site-packages/django_components/template_loader.py", line 23, in get_dirs
    module_parts = settings.SETTINGS_MODULE.split(".")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'

```

In template_loader.py it seems you expect a string in settings.SETTINGS_MODULE, whereas the actual value for it is: `['settings.yaml', '.secrets.yaml']`
These are indeed the config files passed to Dynaconf (see also https://www.dynaconf.com/settings_files/).

TIA
Keep up the good work

**Comment by EmilStenstrom** [comment]
@mjmare seems simple enough to support both formats. Would you be willing to write a PR?

**Comment by mjmare** [comment]
Hmm I don't feel competent enough. 
Besides, I'm not quite sure what the second part of the function is doing. It is trying to locate the component directory of each app? And it does so by 'navigating" from the settings.py file? 
Even accounting for multiple config files (as in Dynaconf) that won't work since the config files can be located anywhere. As long as that is set as the current working directory, Dynaconf will load them. But that will not help in locating the app component dirs.

**Comment by mjmare** [comment]
Would something like this work?
```
        from django.apps import apps
        from pathlib import Path

        def find_app_component_directories():
            app_component_directories = []
            for app_config in apps.get_app_configs():
                app_path = Path(app_config.path)
                component_path = app_path / 'components'
                if component_path.exists() and component_path.is_dir():
                    app_component_directories.append(component_path)
            return app_component_directories
```

**Comment by EmilStenstrom** [comment]
> I'm not quite sure what the second part of the function is doing. It is trying to locate the component directory of each app? And it does so by 'navigating" from the settings.py file? Even accounting for multiple config files (as in Dynaconf) that won't work since the config files can be located anywhere. As long as that is set as the current working directory, Dynaconf will load them. But that will not help in locating the app component dirs.

Yes, it tries to find the root of the project, and looking for app directories from there.

I don't use Dynaconf, so I'm not the right person to fix this.

**Comment by mjmare** [comment]
What do you think of the code snippet I provided to replace the second part of the function that find the app component dirs?

**Comment by mjmare** [comment]
Switched to Django-environs. That works fine.

**Comment by EmilStenstrom** [comment]
Thanks for trying and posting back the results. It’s hard to test your code snippet without learning dynaconf, setting up a test site? And so on.
