### ISSUE TITLE
0.100 breaks string based BASE_DIR

### ISSUE THREAD

**Issue by spapas** [EmilStenstrom/django-components#667]
I'm getting the following error on version 0.100:

```python

Traceback (most recent call last):
  File "C:\progr\py3\ehcg\ehcg\manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\progr\py3\ehcg\ehcg\ehcg\core\apps.py", line 8, in ready
    from ehcg.core.components import Card, CollapsibleCard, CollapsibleFilter, Info, UpContent  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\progr\py3\ehcg\ehcg\ehcg\core\components.py", line 13, in <module>
    class Card(component.Component):
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\component.py", line 115, in __new__
    return super().__new__(mcs, name, bases, attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\component_media.py", line 133, in __new__
    _resolve_component_relative_files(attrs)
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\component_media.py", line 276, in _resolve_component_relative_files
    components_dirs = get_dirs()
                      ^^^^^^^^^^
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\template_loader.py", line 111, in get_dirs
    return loader.get_dirs()
           ^^^^^^^^^^^^^^^^^
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\template_loader.py", line 45, in get_dirs
    component_dirs = app_settings.DIRS
                     ^^^^^^^^^^^^^^^^^
  File "C:\progr\py3\ehcg\venv\Lib\site-packages\django_components\app_settings.py", line 104, in DIRS
    return self.settings.get("dirs", [settings.BASE_DIR / "components"])
                                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

My `BASE_DIR` is like this `BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))`.

My understanding is that you probably need to acount the fact that some people may have a string BASE_DIR (instead of a path).

**Comment by EmilStenstrom** [comment]
@spapas You are likely right. Mind writing up a PR?

**Comment by spapas** [comment]
@EmilStenstrom see #688

**Comment by JuroOravec** [comment]
This has now been released in https://github.com/EmilStenstrom/django-components/releases/tag/0.101 🎉
