### ISSUE TITLE
Incompatiblity with django-webpack and ManifestStaticFilesStorage ?

### ISSUE THREAD

**Issue by stuaxo** [EmilStenstrom/django-components#753]
I'm trying to add django-components to a project that has webpack-loader and uses ManifestStaticFilesStorage.

When I add ComoonentsFileSystemFinder, then collectstatic stops working

```
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # Django components
    #"django_components.finders.ComponentsFileSystemFinder"
]
```

I'm trying to add django-components to a project that has webpack-loader and uses ManifestStaticFilesStorage (this is part of the default settings for wagtail). 

When I add ComoonentsFileSystemFinder, then collectstatic stops working

```
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # Django components
    #"django_components.finders.ComponentsFileSystemFinder"
]
```

```
$ python manage.py collectstatic

Post-processing 'optimiser.css' failed!

Traceback (most recent call last):
  File "~/projects/work/co/project/jao-web/src/manage.py", line 29, in <module>
    main()
  File "~/projects/work/co/project/jao-web/src/manage.py", line 25, in main
    execute_from_command_line(sys.argv)
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
                ^^^^^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 372, in _post_process
    content = pattern.sub(converter, content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 249, in converter
    hashed_url = self._url(
                 ^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 422, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.virtualenvs/project-py311/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 143, in hashed_name
    raise ValueError(
ValueError: The file 'optimiser.css.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x1071e15d0>.
```

**Comment by JuroOravec** [comment]
Hi @stuaxo, thanks for reporting! Could you create and share a minimal project to reproduce this? I haven't used webpack-loader /  Wagtail, and I don't think @EmilStenstrom has either.

Could you give me pointers on how the setup works? 

1. Do you know where the `optimiser.css` is coming from? Is it something that you defined, or generated by wagtail? I assume that the `optimiser.css.map` file that's generated by webpack? And where is the file placed, is it in the static dir?

2. How does the integration with webpack work? Is webpack build step triggered as a separate command before calling `collectstatic`, or does it run during `collectstatic`?

**Comment by stuaxo** [comment]
Thanks for the directions, I'm going to close this for now since I haven't been able to reproduce it.

I think I hadn't fully configured django-component, I'll re-open if I come across this again and can reproduce it.

One thing I would say is that since there is quite a lot to configure when bringing this up, it's quite easy to miss some part and get strange errors, it might be worth detecting some of these and raising errors that point the user at the issue more easily.

**Comment by EmilStenstrom** [comment]
> One thing I would say is that since there is quite a lot to configure when bringing this up, it's quite easy to miss some part and get strange errors, it might be worth detecting some of these and raising errors that point the user at the issue more easily.

Maybe we could have a Django system check telling people if they miss some setting?

**Comment by JuroOravec** [comment]
> I think that would be handy, the TEMPLATES settings are a little more involved than with many other libraries, what with APP_DIRS not being able to be set.

Btw, I think it should be possible to get rid of the TEMPLATES setting, in which case we'd read the template files ourselves.

The trade-off would be that currently it's theoretically possible to render the components template via Django's [`render()`](https://docs.djangoproject.com/en/5.1/topics/http/shortcuts/#render), and that would no longer be possible. Which people shouldn't do anyway, because component's template may contain `{% slot %}` tags, and rendering those outside of a component context is an undefined behavior.

Don't know if the TEMPLATES settings is used for extracting translation messages with `makemessages`.

Moreover, handling the loading of the template files ourselves would allow plugins to pre-process the template as plain string - which would be necessary for a plugin that would allow to write component syntax similar to django-cotton, where one would write `<my-component abc="123" >` instead of `{% my_component abc="123" %}`
