### ISSUE TITLE
problem with WhiteNoise CompressedManifestStaticFilesStorage

### ISSUE THREAD

**Issue by PouriaMzn** [EmilStenstrom/django-components#796]
i just recently update from v0.94 to v0.114 and encountered an issue when   want to use WhiteNoise to server static files in production ```(DEBUG = False)``` and use WhiteNoise compression and caching backend like this:

```
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
```

it throws an error:

```log
[1] Internal Server Error: /favicon.ico
[1] Traceback (most recent call last):
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
[1]     response = get_response(request)
[1]                ^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 785, in __call__
[1]     response = self.process_response(response)
[1]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 798, in process_response
[1]     response.content = render_dependencies(response.content, type="document")
[1]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 335, in render_dependencies
[1]     content_, js_dependencies, css_dependencies = _process_dep_declarations(content_, type)
[1]                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 511, in _process_dep_declarations   
[1]     js=[static("django_components/django_components.min.js")],
[1]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\templatetags\static.py", line 179, in static
[1]     return StaticNode.handle_simple(path)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
[1]     return staticfiles_storage.url(path)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
[1]     return self._url(self.stored_name, name, force)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
[1]     hashed_name = hashed_name_func(*args)
[1]                   ^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
[1]     raise ValueError(
[1] ValueError: Missing staticfiles manifest entry for 'django_components/django_components.min.js'
[1] [30/Nov/2024 11:51:41] "GET /favicon.ico HTTP/1.1" 500 145
```

but i have the ```django_components.min.js``` present in my STATIC_ROOT directory under 
```static-root/django_components/django_components.min.js```

if i change the staticfiles backend to:

```
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
```

it works fine, but now we do not have compression and caching.

and here is my current configuration for django-components:

```
STATICFILES_FINDERS = [
    # Default finders
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # Django components
    "django_components.finders.ComponentsFileSystemFinder",

]

INSTALLED_APPS = [
'django_components',
]

MIDDLEWARE = [
'django_components.middleware.ComponentDependencyMiddleware',
]

COMPONENTS = ComponentsSettings(
    autodiscover= True,
    dirs= [BASE_DIR / 'components'],
    reload_on_template_change= True,
    static_files_forbidden= [
        ".html", ".django", ".dj", ".tpl",
        ".py", ".pyc",
    ],
)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django_components.templatetags.component_tags',
            ],
            'loaders':[(
                'django.template.loaders.cached.Loader', [
                  # Default Django loader
                  'django.template.loaders.filesystem.Loader',
                  # Inluding this is the same as APP_DIRS=True
                  'django.template.loaders.app_directories.Loader',
                  # Components loader
                  'django_components.template_loader.Loader',
                ]
            )],
        },
        
    },
    
    ]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / "components",
]
```

**Comment by JuroOravec** [comment]
Btw @PouriaMzn do you have a `staticfiles.json` generated in your static root directory? If so could you post that as well?

Also, did you experience this only with the template that you've mentioned in https://github.com/EmilStenstrom/django-components/issues/793, or also elsewhere?

If you have capacity, could you look into how Django's `ManifestStaticFilesStorage` works?

From my notes, `staticfiles.json` should be generated when you run `collectstatic` and you have `ManifestStaticFilesStorage` configured.

`django_components/django_components.min.js` is included in `django_components/static/django_components/django_components.min.js`, and so I would expect that this would be picked up by `collectstatic`.

I would need to at which point does `ManifestStaticFilesStorage` generate the `statifiles.json`, and whether it uses the files found by `collectstatic`, or whether it works some other way.

**Comment by PouriaMzn** [comment]
there was problem in my tailwind config that wouldn't let the WhiteNoise collectstatic to work properly, i resolved that and ran ```python manage.py collectstatic --clear --no-input```
and now i'm getting this error instead:

```log
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
[1]     response = get_response(request)
[1]                ^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 785, in __call__
[1]     response = self.process_response(response)
[1]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 798, in process_response
[1]     response.content = render_dependencies(response.content, type="document")
[1]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 335, in render_dependencies
[1]     content_, js_dependencies, css_dependencies = _process_dep_declarations(content_, type)
[1]                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django_components\dependencies.py", line 483, in _process_dep_declarations
[1]     to_load_css_tags = [tag for media in all_medias for tag in media.render_css()]
[1]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\forms\widgets.py", line 123, in <genexpr>
[1]     self.absolute_path(path),
[1]     ^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\forms\widgets.py", line 140, in absolute_path
[1]     return static(path)
[1]            ^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\templatetags\static.py", line 179, in static
[1]     return StaticNode.handle_simple(path)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
[1]     return staticfiles_storage.url(path)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
[1]     return self._url(self.stored_name, name, force)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
[1]     hashed_name = hashed_name_func(*args)
[1]                   ^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "D:\prj\miniconda3\envs\django\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
[1]     raise ValueError(
[1] ValueError: Missing staticfiles manifest entry for 'message_alert\message_alert.css'
```

since the message_alert.css file was actually empty, i deleted i removed it from the compnent, but now i get this error instead:

```
ValueError: Missing staticfiles manifest entry for 'message_alert\message_alert.js'
```
in the genrated ```staticfiles.json``` regarding this message_alert component i have:

```json
{
    "paths": {
        "message_alert/__pycache__/massage_alert.cpython-312.pyc": "message_alert/__pycache__/massage_alert.cpython-312.7aa14eaaef33.pyc",
        "message_alert/__pycache__/message_alert.cpython-312.pyc": "message_alert/__pycache__/message_alert.cpython-312.1070c1e52cbc.pyc",
        "message_alert/message_alert.js": "message_alert/message_alert.a3153e6b6be5.js",
        "message_alert/message_alert.py": "message_alert/message_alert.65eba4bd38b7.py",
        "message_alert/template.html": "message_alert/template.a3695c12d6fa.html"
    },
    "version": "1.1",
    "hash": "84d9526dbbe2"
}
```


and even on the pages that do not have any component in them, i get the same error about Missing staticfiles manifest of other conponents.

**Comment by EmilStenstrom** [comment]
@PouriaMzn That staticfiles.json looks very wrong. In pre-0.100 we required that you added safer_staticfiles to you installed apps to only load static files. Here it seems you've gotten both the .html, .py, and .pyc file, which is clearly not intended. In post-0.100 all this should be handled directly. So there's something wrong here, either with the setup, or in the code.

To troubleshoot this, would you mind seeing with you can recreate it with the [sampleproject](https://github.com/EmilStenstrom/django-components/tree/master/sampleproject)? Either directly by adding WhiteNoise to it, or by putting you message_alert component there and seeing if that works.

**Comment by JuroOravec** [comment]
Btw as for the issue raised by @EmilStenstrom, I think the culprit is this:

```py
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / "components",
]
```

@PouriaMzn The second entry, `BASE_DIR / "components",`, should NOT be there.

Since v0.100, we find the JS / CSS files within the component's dirs with the combination of:
1. `"django_components.finders.ComponentsFileSystemFinder"` in `STATICFILES_FINDERS`
2. And `COMPONENTS.dirs` with e.g. `[BASE_DIR / 'components']`

And we use the two to search the component dirs, but picking only known assets like JS / CSS, while avoiding HTML and Python files.

This was mentoned in the [release notes for v0.100](https://github.com/EmilStenstrom/django-components/releases/tag/0.100):
> - Installation changes:
>    - Instead of defining component directories in `STATICFILES_DIRS`, set them to [`COMPONENTS.dirs`](#dirs).

**Comment by JuroOravec** [comment]
@PouriaMzn I also noticed that you don't have `django.contrib.staticfiles` in the INSTALLED_APPS. Maybe that could be an issue too?

---

I got things working on the `sampleproject`. Only needed to add this to the settings:

```py
STORAGES={
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}
```

And it includes only non-Python / non-HTML files, and even `django_components/django_components.min.js` is hashed properly:

<img width="784" alt="Screenshot 2024-12-01 at 13 22 28" src="https://github.com/user-attachments/assets/7807ca74-c49e-49eb-81f9-6092edbd5c7a">

**Comment by PouriaMzn** [comment]
ok, i think i found the problem, the issue is with the relative path in windows.
In [sampleproject](https://github.com/EmilStenstrom/django-components/tree/master/sampleproject), in the main template as long as we use:

```html
<!DOCTYPE html>
<html>
<head>
    <title>django_components sample projects</title>
</head>
<body>
    {% component "calendar" date=date / %}
</body>
</html>

```

this works fine. 
But if we use calendar_relative component that is included in the project:

```html
<!DOCTYPE html>
<html>
<head>
    <title>django_components sample projects</title>
</head>
<body>
    {% component "calendar_relative" date=date / %}
</body>
</html>

```

it raises this error:

```
ValueError: Missing staticfiles manifest entry for 'calendar\calendar.css'
```

and in the ```staticfiles.json``` we have:

```json
{
  "paths": {
    "calendar/calendar.css": "calendar/calendar.87b00e32bb6a.css",
    "calendar/calendar.js": "calendar/calendar.168389a42504.js"
  },
  "version": "1.1",
  "hash": "0ae184be0904"
}

```

so basically, in the manifest we have ```calendar/calendar.css``` but somehow djago is looking for ```'calendar\calendar.css'```

In my components i changed all the paths to be relative to COMPONENTS.dirs and solved my problem, so 
```
"calendar.html"  --->>   "calendar/calendar.html"
"calendar.css"   --->>    "calendar/calendar.css"
"calendar.js"    --->>    "calendar/calendar.js"
```

**Comment by JuroOravec** [comment]
@PouriaMzn Interesting. Could you help me confirm that it relates to how the paths are resolved on the component classes?

E.g. take the relative calendar component, change the file names back to `calendar.html`, etc. And then right after the class definition, print out the resolved paths:

```python
class CalendarRelative(Component):
    template_name = "calendar.html"
    ...

print("HTML: ", CalendarRelative.template_name)
print("JS: ", CalendarRelative.Media.js)
print("CSS: ", CalendarRelative.Media.css)
```

**Comment by PouriaMzn** [comment]
```python

@register("calendar_relative")
class CalendarRelative(Component):
    template_name = "calendar.html"
    def get_context_data(self, date):
        return {
            "date": date,
        }

    def get(self, request, *args, **kwargs):
        context = {
            "date": request.GET.get("date", ""),
        }
        return self.render_to_response(context)

    class Media:
        css = "calendar.css"
        js = "calendar.js"

print("\n--------------------------------------------\n")
print("HTML: ", CalendarRelative.template_name)
print("JS: ", CalendarRelative.Media.js)
print("CSS: ", CalendarRelative.Media.css)
print("\n--------------------------------------------\n")

```

prints out these:

```
HTML:  calendar\calendar.html
JS:  ['calendar\\calendar.js']
CSS:  {'all': ['calendar\\calendar.css']}
```

**Comment by JuroOravec** [comment]
Btw, @PouriaMzn, do you run your Python locally, or in Docker / VM? If locally, could you try if the changes in https://github.com/EmilStenstrom/django-components/pull/799/files#diff-bdb1917504a9c50a51e7fdf49498d5db3ce0233be9eb81b13938d4b3dcd5efc3R295 (lines 296-310) to fix your problem?

E.g. if you're running it locally, and you have Python virtual env, then the path could be something like:

```
./.venv/lib/python3.11/site-packages/django_components/component_media.py
```

**Comment by PouriaMzn** [comment]
This change definitely solved the issue, thanks 🤘

**Comment by JuroOravec** [comment]
@PouriaMzn The fix has been released in [v0.115](https://github.com/EmilStenstrom/django-components/releases/tag/0.115) :tada:
